manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: multi_remote
      url-base: https://github.com/Boettner-eric/zmk-multi-module
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: multi
      remote: multi_remote
      revision: main
  self:
    path: config
